### PR TITLE
Refactor if-chains, add to janet

### PR DESCRIPTION
**Pull request by MichalMarsalek**
1 more point from #328

### CODE REVIEW

**Comment by MeWhenI** [comment]
Janet could also use `cond` for implementing `ConditionalOp`, and I imagine some other langs might also be able to pull the IfChain logic over to conditionals.

**Comment by MichalMarsalek** [comment]
Ah, right. It might make sense to merge the two (If and ConditionalOp) completely, but for now, I just used the logic for ConditionalOp too.

**Comment by MeWhenI** [comment]
Is there a plugin that currently exists to try inverting the condition and then swapping the alternate and consequent statements? Since if-chaining as I understand it only expands the alternate, this would be beneficial. Maybe thats for a separate issue though, PR otherwise looks good.

**Comment by MichalMarsalek** [comment]
> Is there a plugin that currently exists to try inverting the condition and then swapping the alternate and consequent statements? Since if-chaining as I understand it only expands the alternate, this would be beneficial. Maybe thats for a separate issue though, PR otherwise looks good.

Such plugin should probably be added, but I wonder if there's ever a reason to nest the conditions in a "nonstandard" way in the Polygolf program?

**Comment by MeWhenI** [comment]
What do you mean by "nonstandard" nesting?

**Comment by MichalMarsalek** [comment]
> What do you mean by "nonstandard" nesting?

One that is not
```c
if(cond){

}
else{
  if (cond){

  }
  else{
    if(cond){
    
    }
    else{
      
    }
  }
}
```

**Pull request merged**
